runtime: python27
api_version: 1
threadsafe: true

builtins:
- deferred: on

libraries:
- name: ssl
  version: latest

handlers:
- url: /static
  static_dir: dist/static
  secure: always
- url: /.*
  script: run.app
  secure: always

skip_files:
- ^(.*/)?.*/assets/.*$
- ^(.*/)?.*/build/.*$
- ^(.*/)?.*/test/.*$
- ^(.*/)?.*/templates/.*$
- ^(.*/)?.*/node_modules/.*$
- ^(client/.*)
- ^(assets/.*)
- ^(build/.*)
- ^(test/.*)
- ^(templates/.*)
- ^(node_modules/.*)
- ^(.*/)?#.*#$
- ^(.*/)?.*~$
- ^(.*/)?.*\.DS_Store$
- ^(.*/)?.*\.py[co]$
- ^(.*/)?.*/RCS/.*$
- ^(.*/)?\..*$